config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: %i[new create destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to @restaurant, notice: 'Restaurant deleted.'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @review = Review.new(review_params)
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :category, collection: %w[chinese italian japanese french belgian]%>
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="col-6 m-3 border rounded shadow">
    <h1>Edit Restaurant</h1>
    <%= render 'form', restaurant: @restaurant %>
    <div class="my-5 p-1 bg-white d-flex justify-content-center">
    <%= link_to restaurants_path, class: 'btn btn-success btn-lg' do %>
      <i class="fas fa-home"></i>
    <% end %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container d-flex flex-column">
  <div class="d-flex justify-content-around">
    <h1 class="m-2 p-2 text-center">Restaurants</h1>
    <%= link_to new_restaurant_path, class: 'ml-3 btn btn-success btn-sm' do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>
  <div class="row justify-content-center">
  <% @restaurants.each do |restaurant| %>
    <div class="col-3 m-1 p-1 border rounded shadow-sm bg-white d-flex flex-column">
      <img src=<%= "http://loremflickr.com/280/280/#{restaurant.category}restaurant" %> width="280" height="280">
      <div class="flex-grow-1 m-1">
        <h2><%= restaurant.name %></h2>
        <p><%= restaurant.category %></p>
      </div>
      <div class="m-1 d-flex align-items-end justify-content-end">
          <%= link_to restaurant_path(restaurant), class: 'ml-3 btn btn-success btn-sm' do %>
            <i class="fas fa-info-circle"></i>
          <% end %>
          <%= link_to edit_restaurant_path(restaurant), class: 'ml-3 btn btn-primary btn-sm' do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-3 btn btn-danger btn-sm' do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
    </div>
  <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="col-6 m-3 border rounded shadow">
    <h1>Add New Restaurant</h1>
    <%= render 'form', restaurant: @restaurant %>
    <div class="my-5 p-1 bg-white d-flex justify-content-center">
    <%= link_to restaurants_path, class: 'btn btn-success btn-lg' do %>
      <i class="fas fa-home"></i>
    <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-6 m-1 p-1 border rounded shadow bg-white d-flex flex-column">
      <img src=<%= "http://loremflickr.com/400/400/#{@restaurant.category}restaurant" %> alt="" width="400" height="400">
      <div class="flex-grow-1 m-1">
        <h1><%= @restaurant.name %></h1>
        <p><%= @restaurant.category %></p>
        <p>Address: <%= @restaurant.address %></p>
        <div class="p-3 border rounded bg-light">
          <h3>REVIEWS</h3>
          <ul>
            <% @reviews.each do |review| %>
              <li>
                <%= review.content %>
                <%= link_to 'Remove', restaurant_review_path(review), method: :delete, data: { confirm: 'Are you sure?'} %>
              </li>
            <% end %>
          </ul>
          <%= link_to new_restaurant_review_path(@restaurant), class: 'ml-3 btn btn-warning btn-lg' do %>
            <span><i class="fas fa-star-half-alt"></i>Add Review</span>
          <% end %>
        </div>
      </div>
      <div class="m-1 d-flex align-items-end justify-content-between">
          <%= link_to restaurants_path, class: 'btn btn-success btn-lg' do %>
            <i class="fas fa-home"></i>
          <% end %>
          <div>
          <%= link_to edit_restaurant_path(@restaurant), class: 'ml-3 btn btn-primary btn-lg' do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-3 btn btn-danger btn-lg' do %>
            <i class="fas fa-trash"></i>
          <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add a new review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating, collection: 0..5, prompt: "Give your review", selected: 0 %>
    <%= f.input :content %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>